name: Backend Continuous Integration

on:
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    branches:
      - main

jobs:
  LINT_JOB:
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Check the Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Checkout Run Lint
      working-directory: starter/backend
      run: pipenv run lint

  TEST_JOB:
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v4

    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: checkout  Test
      working-directory: starter/backend 
      run: pipenv install pytest && pipenv run test

      
  BUILD_JOB:
    needs: [LINT_JOB, TEST_JOB]
    runs-on: ubuntu-latest
    
    steps:
    - name: Check the Repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      working-directory: starter/backend
      run: |
        docker build --tag mp-backend:latest .